<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesSeed extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::insert('INSERT INTO countries(title, code, icon) VALUES
        ("European Union", "eu", "eu.png"),
        ("Afghanistan", "af", "af.png"),
        ("Albania", "al", "al.png"),
        ("Algeria", "dz", "dz.png"),
        ("Andorra", "ad", "ad.png"),
        ("Angola", "ao", "ao.png"),
        ("Antigua", "ag", "ag.png"),
        ("Argentina", "ar", "ar.png"),
        ("Armenia", "am", "am.png"),
        ("Australia", "au", "au.png"),
        ("Austria", "at", "at.png"),
        ("Azerbaijan", "az", "az.png"),
        ("Bahamas", "bs", "bs.png"),
        ("Bahrain", "bh", "bh.png"),
        ("Bangladesh", "bd", "bd.png"),
        ("Barbados", "bb", "bb.png"),
        ("Belarus", "by", "by.png"),
        ("Belgium", "be", "be.png"),
        ("Bolivia", "bo", "bo.png"),
        ("Bosnia Herzegowina", "ba", "ba.png"),
        ("Botswana", "bw", "bw.png"),
        ("Brazil", "br", "br.png"),
        ("Bulgaria", "bg", "bg.png"),
        ("Burkina Faso", "bf", "bf.png"),
        ("Cambodia", "kh", "kh.png"),
        ("Cameroon", "cm", "cm.png"),
        ("Cayman Islands", "ky", "ky.png"),
        ("Canada", "ca", "ca.png"),
        ("Chad", "td", "td.png"),
        ("Chile", "cl", "cl.png"),
        ("China", "cn", "cn.png"),
        ("Colombia", "co", "co.png"),
        ("Congo", "cd", "cd.png"),
        ("Costa Rica", "cr", "cr.png"),
        ("Croatia", "hr", "hr.png"),
        ("Cuba", "cu", "cu.png"),
        ("Cyprus", "cy", "cy.png"),
        ("Czech Republic", "cz", "cz.png"),
        ("Denmark", "dk", "dk.png"),
        ("Dominican Republic", "do", "do.png"),
        ("Ecuador", "ec", "ec.png"),
        ("Egypt", "eg", "eg.png"),
        ("El Salvador", "sv", "sv.png"),
        ("Estonia", "ee", "ee.png"),
        ("Eritrea", "er", "er.png"),
        ("Ethiopia", "et", "et.png"),
        ("Falkland Islands", "fk", "fk.png"),
        ("Faroe Islands", "fo", "fo.png"),
        ("Fiji", "fj", "fj.png"),
        ("Finland", "fi", "fi.png"),
        ("France", "fr", "fr.png"),
        ("French Polynesia", "pf", "pf.png"),
        ("Germany", "de", "de.png"),
        ("Georgia", "ge", "ge.png"),
        ("Ghana", "gh", "gh.png"),
        ("Gibraltar", "gi", "gi.png"),
        ("Greece", "gr", "gr.png"),
        ("Greenland", "gl", "gl.png"),
        ("Guam", "gu", "gu.png"),
        ("Guatemala", "gt", "gt.png"),
        ("Haiti", "ht", "ht.png"),
        ("Honduras", "hn", "hn.png"),
        ("Hungary", "hu", "hu.png"),
        ("Iceland", "is", "is.png"),
        ("India", "in", "in.png"),
        ("Indonesia", "id", "id.png"),
        ("Iran", "ir", "ir.png"),
        ("Iraq", "iq", "iq.png"),
        ("Ireland", "ie", "ie.png"),
        ("Israel", "il", "il.png"),
        ("Italy", "it", "it.png"),
        ("Jamaica", "jm", "jm.png"),
        ("Japan", "jp", "jp.png"),
        ("Jordan", "jo", "jo.png"),
        ("Kazakhstan", "kz", "kz.png"),
        ("Kenya", "ke", "ke.png"),
        ("Kyrgyzstan", "kg", "kg.png"),
        ("Kuwait", "kw", "kw.png"),
        ("Latvia", "lv", "lv.png"),
        ("Laos", "la", "la.png"),
        ("Lebanon", "lb", "lb.png"),
        ("Liberia", "lr", "lr.png"),
        ("Libya", "ly", "ly.png"),
        ("Liechtenstein", "li", "li.png"),
        ("Lithuania", "lt", "lt.png"),
        ("Luxemburg", "lu", "lu.png"),
        ("Macau", "mo", "mo.png"),
        ("Macedonia", "mk", "mk.png"),
        ("Madagascar", "mg", "mg.png"),
        ("Malawi", "mw", "mw.png"),
        ("Malaysia", "my", "my.png"),
        ("Maldives", "mv", "mv.png"),
        ("Mali", "ml", "ml.png"),
        ("Marshall Islands", "mh", "mh.png"),
        ("Mauritania", "mr", "mr.png"),
        ("Malta", "mt", "mt.png"),
        ("Mexico", "mx", "mx.png"),
        ("Micronesia", "fm", "fm.png"),
        ("Moldova", "md", "md.png"),
        ("Monaco", "mc", "mc.png"),
        ("Mongolia", "mn", "mn.png"),
        ("Montenegro", "me", "me.png"),
        ("Morocco", "ma", "ma.png"),
        ("Mozambique", "mz", "mz.png"),
        ("Myanmar", "mm", "mm.png"),
        ("Namibia", "na", "na.png"),
        ("Nepal", "np", "np.png"),
        ("Netherlands", "nl", "nl.png"),
        ("New Guinea", "pg", "pg.png"),
        ("New Zealand", "nz", "nz.png"),
        ("Nicaragua", "ni", "ni.png"),
        ("Niger", "ne", "ne.png"),
        ("Nigeria", "ng", "ng.png"),
        ("Norway", "no", "no.png"),
        ("North Korea", "kp", "kp.png"),
        ("Norfolk Island", "nf", "nf.png"),
        ("Oman", "om", "om.png"),
        ("Pakistan", "pk", "pk.png"),
        ("Palestine", "ps", "ps.png"),
        ("Panama", "pa", "pa.png"),
        ("Paraguay", "py", "py.png"),
        ("Peru", "pe", "pe.png"),
        ("Philippines", "ph", "ph.png"),
        ("Poland", "pl", "pl.png"),
        ("Portugal", "pt", "pt.png"),
        ("Puerto Rico", "pr", "pr.png"),
        ("Qatar", "qa", "qa.png"),
        ("Romania", "ro", "ro.png"),
        ("Russia", "ru", "ru.png"),
        ("Rwanda", "rw", "rw.png"),
        ("Samoa", "ws", "ws.png"),
        ("San Marino", "sm", "sm.png"),
        ("Saudi Arabia", "sa", "sa.png"),
        ("Senegal", "sn", "sn.png"),
        ("Seychelles", "sc", "sc.png"),
        ("Sierra Leone", "sl", "sl.png"),
        ("Singapore", "sg", "sg.png"),
        ("Slovakia", "sk", "sk.png"),
        ("Slovenia", "si", "si.png"),
        ("Somalia", "so", "so.png"),
        ("South Africa", "za", "za.png"),
        ("South Korea", "kr", "kr.png"),
        ("Spain", "es", "es.png"),
        ("Sri Lanka", "lk", "lk.png"),
        ("Sudan", "sd", "sd.png"),
        ("Swaziland", "sz", "sz.png"),
        ("Sweden", "se", "se.png"),
        ("Switzerland", "ch", "ch.png"),
        ("Syria", "sy", "sy.png"),        
        ("Taiwan", "tw", "tw.png"),
        ("Thailand", "th", "th.png"),
        ("Tajikistan", "tj", "tj.png"),
        ("Tonga", "to", "to.png"),
        ("Trinidad", "tt", "tt.png"),
        ("Tunisia", "tn", "tn.png"),
        ("Turkey", "tr", "tr.png"),
        ("Turkmenistan", "tm", "tm.png"),
        ("Uganda", "ug", "ug.png"),
        ("Ukraine", "ua", "ua.png"),
        ("United Arab Emirates", "ae", "ae.png"),
        ("United Kingdom", "uk", "uk.png"),
        ("Uruguay", "uy", "uy.png"),
        ("USA", "us", "us.png"),
        ("Uzbekistan", "uz", "uz.png"),
        ("Venezuela", "ve", "ve.png"),
        ("Vietnam", "vn", "vn.png"),
        ("Yemen", "ye", "ye.png"),
        ("Zambia", "zm", "zm.png"),
        ("Zimbabwe", "zw", "zw.png")');
    }
}
